(* Overall document structure *)

S ::= geophysical-document | ephemeredes-document | bodies-document;

<geophysical-document> ::=
    <garbage>,
    <separator>, file-header,
    (<ws>        geophysical-data)?
    (<ws>        physical-properties)?
    (<ws>        dynamical-characteristics)?
    <separator> <garbage> <select-prompt>;

<ephemeredes-document> ::=
    <ws "Working" " ...", spinning-bar>
    <garbage>
    <separator> <ephemeris-header>
    <separator> <targeting>
    <separator> time-frame
    <separator> <ephemeris-metadata>
    <separator> <ephemeris-legend>
    <separator> ephemeredes
    <separator> <coordinate-system-description>
    <separator>
    <garbage>
    <select-prompt>;

spinning-bar ::= (forward-slash | pipe | back-slash | hyphen | ws | backspace)+;

forward-slash ::= "/";
pipe ::= "|";
back-slash ::= "\\";
hyphen ::= "-";

ephemeris-header ::=
"Ephemeris / PORT_LOGIN" ws date ws time ws year ws "Pasadena, USA    / Horizons"

targeting ::=
"Target body name:" ws body-name ws "(" body-id ")" ws "{source: " #"[\w]+" "}" ws
"Center body name:" ws body-name ws "(" body-id ")" ws "{source: " #"[\w]+" "}" ws
"Center-site name: BODY CENTER"

time-frame ::= start-time, stop-time, step-size;

start-time ::= <"Start time      : "> timestamp <ws>;
stop-time ::= <"Stop  time      : "> timestamp <ws>;
step-size ::= <"Step-size       : "> duration <ws>;

ephemeris-metadata ::=
"Center geodetic : 0.00000000,0.00000000,0.0000000 {E-lon(deg),Lat(deg),Alt(km)}" ws
"Center cylindric: 0.00000000,0.00000000,0.0000000 {E-lon(deg),Dxy(km),Dz(km)}" ws
"Center radii    : 6378.1 x 6378.1 x 6356.8 km     {Equator, meridian, pole}" ws
"Output units    : " ("KM-D" | "AU-D") ws
"Output type     : GEOMETRIC cartesian states" ws
"Output format   : 3 (position, velocity, LT, range, range-rate)" ws
"Reference frame : ICRF/J2000.0" ws
"Coordinate " ("systm" | "system description" ) ": Ecliptic and Mean Equinox of Reference Epoch";

ephemeris-legend ::=
"JDTDB" ws "X" ws "Y" ws "Z" ws "VX" ws "VY" ws "VZ" ws "LT" ws "RG" ws "RR";

ephemeredes ::=
<"$$SOE"> <ws> (ephemeris <ws>)+ <"$$EOE">;

ephemeris ::=
    julian-day-number <equals> timestamp
    <ws> x-position <ws> y-position <ws> z-position
    <ws> x-velocity <ws> y-velocity <ws> z-velocity
    <ws> lt <ws> range <ws> range-rate;

julian-day-number ::= float;

x-position ::= <"X" equals>? sci-not;
y-position ::= <"Y" equals>? sci-not;
z-position ::= <"Z" equals>? sci-not;

x-velocity ::= <"VX" equals>? sci-not;
y-velocity ::= <"VY" equals>? sci-not;
z-velocity ::= <"VZ" equals>? sci-not;

lt ::= <"LT" equals>? sci-not;
range ::= <"RG" equals>? sci-not;
range-rate ::= <"RR" equals>? sci-not;

coordinate-system-description ::=
"Coordinate system description:" ws

"  Ecliptic and Mean Equinox of Reference Epoch" ws

"    Reference epoch: J2000.0" ws
"    XY-plane: plane of the Earth's orbit at the reference epoch" ws
"              Note: obliquity of 84381.448 arcseconds wrt ICRF equator (IAU76)" ws
"    X-axis  : out along ascending node of instantaneous plane of the Earth's" ws
"              orbit and the Earth's mean equator at the reference epoch" ws
"    Z-axis  : perpendicular to the xy-plane in the directional (+ or -) sense" ws
"              of Earth's north pole at the reference epoch." ws

"  Symbol meaning [" "1 au= 149597870.700 km, "? "1 day=" ws? "86400.0 s]:" ws

"    JDTDB    Julian Day Number, Barycentric Dynamical Time" ws
"      X      X-component of position vector (" ("km" | "au") ")" ws
"      Y      Y-component of position vector (" ("km" | "au") ")" ws
"      Z      Z-component of position vector (" ("km" | "au") ")" ws
"      VX     X-component of velocity vector (" ("km" | "au") "/day)" ws
"      VY     Y-component of velocity vector (" ("km" | "au") "/day)" ws
"      VZ     Z-component of velocity vector (" ("km" | "au") "/day)" ws
"      LT     One-way down-leg Newtonian light-time (day)" ws
"      RG     Range; distance from coordinate center (" ("km" | "au") ")" ws
"      RR     Range-rate; radial velocity wrt coord. center (" ("km" | "au") "/day)" ws

"Geometric states/elements have no aberrations applied." ws

" Computations by ..." ws
"     Solar System Dynamics Group, Horizons On-Line Ephemeris System" ws
"     4800 Oak Grove Drive, Jet Propulsion Laboratory" ws
"     Pasadena, CA  91109   USA" ws
"     Information: http://ssd.jpl.nasa.gov/" ws
"     Connect    : telnet://ssd.jpl.nasa.gov:6775  (via browser)" ws
"                  http://ssd.jpl.nasa.gov/?horizons" ws
"                  telnet ssd.jpl.nasa.gov 6775    (via command-line)" ws
"     Author     : Jon.D.Giorgini@jpl.nasa.gov"


(* General data types *)

<garbage> ::= (#"[\d\[\?1h\= \^\>l]" | "K" | escape | <ws>)+;
separator ::= <ws>, (short-sep | long-sep), <ws>, separator?;
short-sep ::= #"\*{79}";
long-sep ::= #"\*{110}";

newline ::= "\n" | "\r" | "\r\n";
space ::= #"[\s\n\r]";
ws ::= space*;
backspace ::= "\u0008";
escape ::= "\u001B"
delete ::= "\u007F";

value ::= integer | approximate-integer | integer-with-error |
          float | float-with-error | sci-not |
          timestamp | duration |
          dipole-tilt-offset-value |
          fig-offset-value |
          flattening-value |
          gm-1-sigma-value |
          magnetic-moment-value |
          angular-value |
          angular-value-with-error |
          offset-value;

<digit> ::= #"\d";
integer ::= #"[-\+]?\d+" | comma-separated-integer;
comma-separated-integer ::= #"\d?\d?\d?,(\d\d\d,)+\d\d\d";
<integer-with-error> ::= integer <#"\(?\+\-\d+\)?">;
float ::= #"\-?\d*\.\d*";
<float-with-error> ::= float <error>
<error> ::= #"\(\d\+\-\d\)" | ( space* "+-" space* float);
<approximate-integer> ::= #"~\d+";
<dipole-tilt-offset-value> ::= #"\d+\.?\d*de?g/\d+\.\d+Rp";
<fig-offset-value> ::= "0.19+-01";
<flattening-value> ::= #"\d/\d\d\d\.\d\d\d";
<gm-1-sigma-value> ::= #"\+\- ?\d\.?\d+";
<magnetic-moment-value> ::=  #"< 1x10\^\-\d";
<angular-value> ::= #'\d+\.\d+\"';
<angular-value-with-error> ::= #"\d.\d\d' \+/\- \d\.\d'";
<offset-value> ::= #"\d+d? ?\/ ?\d+d?";

sci-not ::= significand <ws "("? sci-not-separator> exponent <")"?>
<sci-not-separator> := (("x" | "*") ws "10^") | "E";
significand ::= float | integer;
exponent ::= integer;

timestamp ::= era?, <space>, date, <ws>, time, <space>, time-zone?;

date ::= (year <"-"> month <"-"> day) |
         (month <" "+> day <", "> year) |
         (day-of-week <" "+> month <" "+> day);

era ::= "A.D."
year ::= integer;
month ::= "Jan" | "Feb" | "Mar" | "Apr" | "May" | "Jun" | "Jul" | "Aug" | "Sep" | "Oct" | "Nov" | "Dec";
day ::= integer
time ::= hour-of-day <":"> minute-of-hour (<":"> second-of-minute (<"."> millisecond-of-second)?)?;
day-of-week ::= "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";

hour-of-day ::= integer;
minute-of-hour ::= integer;
second-of-minute ::= integer;
millisecond-of-second ::= integer;

(* TODO: property parse a seconds measurement like 22.4, currently this things there are 4 milliseconds *)
duration ::= years? days? (hours <ws? ("h" | "hr") ws>)? (minutes <ws? ("m" | "minutes") ws?>)? (seconds <"s">)?;
years ::= float <("y" | "yr" | "yrs")>;
days ::= (float | integer) <ws? "d" ws?>;
hours ::= float | float-with-error | integer;
minutes ::= integer;
seconds ::= float | integer

time-zone ::= "UT" | "TDB";

(* Units using the UN/CEFACT Common Codes for Units of Measurement
    See http://www.unece.org/fileadmin/DAM/cefact/recommendations/rec20/rec20_Rev9e_2014.xls
*)

unit-23  ::= <"gm cm^-3" | "g cm^-3" | "g/cm^3">;
unit-2A  ::= <"rad/s" | "rad s^-1">;
unit-A62 ::= <"erg/gm*s">;
unit-BAR ::= <"bar">;
unit-D54 ::= <"W/m^2" | "Wm^2">; (* [sic] *)
unit-D61 ::= "'";
unit-D62 ::= '"';
unit-DD  ::= <"deg">;
unit-H20 ::= <"km^3">;
unit-KEL ::= <"K">;
unit-KGM ::= <"kg">;
unit-KMT ::= <"km">;
unit-M62 ::= <"("? ("km/s" | "km s^-1") ")"?>;
unit-MSK ::= <"m" ((" "? "s^-2") | "/s^2")>;
unit-SEC ::= <"s">;

(* TODO: find out what the unit code for this is *)
unit-gauss-rp3 ::= "gauss Rp^3" | "gauss-Rp^3";
unit-degrees-per-day ::= "deg/d" | "dg/d";

(* Domain-specific data types *)

(*
  body names are allowed to have spaces, but currently limited to only one,
  we don't want to match excess whitespace between words.
*)

body-name ::= #"\w+(\w|( \w))*\w+";
body-id ::= integer;

(* Document proper *)

file-header ::=
    revision-date   <space+>
    body-name       <space+>
    body-id         <space+>
    <#"\/ \d"?>

revision-date ::= <"Revised: "> date;

dynamical-characteristics ::= <dynamical-characteristics-header>  (<ws> geophysical-field)+;
geophysical-data ::=  <geophysical-data-header> (<ws> geophysical-field)+;
physical-properties ::= <physical-properties-header>  (<ws> geophysical-field)+;

<geophysical-field> ::=
    <"Mass layers:"> |
    <obliquity-source> |
    <surface-area-title> |
    a-roche-ice |
    atmospheric-mass |
    atmospheric-pressure |
    core-radius |
    crust-mass |
    density |
    dipole-tilt-offset |
    equatorial-gravity |
    equatorial-radius |
    escape-velocity |
    fig-offset |
    flattening |
    fluid-core-radius |
    g-o |
    g-polar |
    geometric-albedo |
    gm-1-sigma |
    grav-spectral-fact |
    heat-flow-mass |
    hill-sphere-radius |
    hydrostatic-flattening |
    inferred-rotation-period |
    inner-core-mass |
    inner-core-radius |
    j2 |
    ks |
    m |
    magnetic-moment |
    mantle-mass |
    mass |
    mass-ratio-from-sun |
    maximum-angular-diameter |
    mean-daily-motion |
    mean-radius |
    mean-sidereal-orbital-period-days |
    mean-sidereal-orbital-period-years |
    mean-solar-day |
    mean-temperature |
    moment-of-inertia |
    monent-of-inertia-upper-bound |
    obliquity-to-orbit |
    ocean-mass |
    offset |
    orbit-velocity |
    outer-core-mass |
    polar-axis |
    polar-gravity |
    polar-radius |
    potential-love-k2 |
    rocky-core-mass |
    rotation-rate |
    semi-major-axis |
    sidereal-rotation-period |
    solar-constant |
    standard-gravitational-parameter |
    surface-area-land |
    surface-area-sea |
    topo-spectral-fact |
    visual-magnitude |
    visual-magnitude-opposition |
    volume |
    y-factor;

equals ::= space* "=" space*;

geophysical-data-header ::= "GEO"? "PHYSICAL DATA" ws "(update" "d"? ws date "):";
dynamical-characteristics-header ::= "DYNAMICAL CHARACTERISTICS:";
physical-properties-header ::= "PHYSICAL PROPERTIES (revised " date "):";

a-roche-ice ::= <"A_roche(ice)/Rp" | "Aroche(ice)/Rp"> <equals> value;
atmospheric-mass ::= <"Atmos"> <equals> value <" "> unit-KGM;
atmospheric-pressure ::= <("Atm." | "Atmos.") " pressure"> (<" ("> unit-BAR <")">)? <equals> value? (<" "> unit-BAR)?;
core-radius ::= <"Core radius ("> unit-KMT <")"> <equals> value;
crust-mass ::= <"crust"> <equals> value <" "> unit-KGM;
density ::= <"Density">, <",">? <" "> <"("?> unit-23 <")"?> <equals> value;
dipole-tilt-offset ::= <"Dipole tilt/offset"> <equals> value;
equatorial-gravity ::= <("Equ. " "grav" "ity"? ", "?)? "ge"? ","? space+ "("?> unit-MSK <")"?> <" (equatorial)">? <equals> value;
equatorial-radius ::= <"Equatorial" | "Equ." | "Equat."> <" "> <"R" | "r"> <"adius"> (<", Re"> | (<", "> unit-KMT) | <" (1 " unit-BAR ")">) <equals> value <" "?> unit-KMT?;
escape-velocity ::= <"Escape" ws ("vel." | "velocity") ws?> unit-M62? <equals> value <ws> unit-M62?;
fig-offset ::= <"Fig. offset (Rcf-Rcm)"> <equals> value (<" "> unit-KMT)?;
flattening ::= <"Flattening" ", f"?> <equals> value?;
fluid-core-radius ::= <"Fluid core rad"> <equals> value <" "> unit-KMT;
(* equatorial & polar gravity? units seem right. What is g-o? *)
g-o ::= <"go, "> unit-MSK <equals> value;
g-polar ::= <"Pol. grav, "? "gp" ","? " " "("?> unit-MSK <")"?  " "? "(polar)"?> <equals> value;
geometric-albedo ::= <"Geometric albedo"> <equals> value;
gm-1-sigma ::= <"GM 1-sigma" ws? "(" ws? ( "km^3 s^-2" | "km^3/s^2" ) ws? ")"> <equals> value;
grav-spectral-fact ::= <"Grav spectral fact u"> <equals> value;
heat-flow-mass ::= <"Heat flow/mass (x10^"> exponent <")"> <equals>  value? (<ws> unit-A62)?;
hill-sphere-radius ::= <"Hill's sphere" ws ("rad." | "radius") ","? ws "Rp"?> <equals> value;
hydrostatic-flattening ::= <"Hydrostatic flat., fh"> <equals> value;
inferred-rotation-period ::= <"Inferred rot. period"> <equals> value;
inner-core-mass ::= <"inner core     = "> value <" "> unit-KGM;
inner-core-radius ::= <"Inner core rad   = "> value <" "> unit-KMT;
j2 ::= <"J2  (GEM T2, 1990)       = "> value;
ks ::= <"ks = 3*J2/m"> <equals> value;
m ::= <"m = w^2a^3/GM"> <equals> value;
magnetic-moment ::= <"Mag. mom (gauss Rp^3)" | "Magnetic moment" | "Mag.dip.mom(gauss-Rp^3)"> <equals> value <ws unit-gauss-rp3>?;
mantle-mass ::= <"mantle         = "> value <" "> unit-KGM;
mass ::= <"Mass" ","? " " "("? "10^"> exponent <" "?> unit-KGM <" "? ")"?> <equals> value;
mass-ratio-from-sun ::= <"Mass ratio " ("(Sun/" body-name ")" | "(sun/plnt)")> <equals> value;
maximum-angular-diameter ::= <"Max. angular diam."> <equals> value;
mean-daily-motion ::= <"Mean daily motion" ", n"?> <equals> value <ws> <unit-degrees-per-day>;
mean-radius ::= <"Volumetric "? ("M" | "m") "ean radius" " "? ", "? "("?> unit-KMT? <")"? > <equals> value <ws?> unit-KMT?;
<mean-sidereal-orbit-label> ::= <"Mean"? ws ("sidereal" | "Sidereal") ws (("orb" "."?)  | "orbit")? ws? (("per" "."?) | "period")>;
mean-sidereal-orbital-period-years ::= <mean-sidereal-orbit-label> <equals> float <ws> <("yrs" | "y" | "yr")?>;
mean-sidereal-orbital-period-days ::= <mean-sidereal-orbit-label> <equals> float <ws> <("d" | "days")>;
mean-solar-day ::= <"Mean solar day" ", days"?> <equals> value <" d"?>;
mean-temperature ::= (<("Atmos. temp. (1 " unit-BAR ")")> | (<"Mean Temperature"> <" (" | ", "> unit-KEL <")"?>)) <equals> value? <ws> unit-KEL?;
moment-of-inertia ::= <("Mom. of Inertia" | "Moment of inertia" | "Mom. of inert. I/MRo^2")> <equals> value?;
monent-of-inertia-upper-bound ::= <"I/MRo^2 (upper bound)"> <equals> value;
ocean-mass ::= <"oceans"> <equals> value <" "> unit-KGM;
obliquity-to-orbit ::= <"Obliquity to orbit"> <"[1]"?> <", "?> unit-DD? <equals> value <" "?> unit-DD?;
offset ::= <"Offset (lat./long.)"> <equals> value <ws "dg/dg">?;
orbit-velocity ::= <"Mean"? ws ("Orbit" | "orbit") ws ("vel." | "velocity") ","? ws> unit-M62? <equals> value <ws> unit-M62?;
outer-core-mass ::= <"outer core     = "> value <" "> unit-KGM;
polar-gravity ::= <"Polar gravity "> unit-MSK <equals> value?;
polar-axis ::= <"Polar axis, "> unit-KMT <equals> value;
polar-radius ::= <"Polar radius ("> unit-KMT <")"> <equals> value;
potential-love-k2 ::= <("Potential Love # k2" | "Love no., k2")> <equals> <"~"?> value?;
rocky-core-mass ::= <"Rocky core mass (Mc/M)"> <equals> value?;
rotation-rate ::= <"Mean "? ("R" | "r") "ot. " ("R" | "r") "ate" ","? " "? "("?> (<"x"? "10^"> exponent)? <" "> (unit-SEC | unit-2A) <")"?> <equals> value;
semi-major-axis ::= <"Semi-major axis"> <equals> value?;
solar-constant ::= <("Solar constant, " unit-D54) | "Planetary Solar Const"> <equals> value  (<ws "("?> unit-D54 <")"?>)?;
sidereal-rotation-period ::= <("Sidereal rot. period" | "Sidereal period, hr" | "Sidereal period" | "Rotation period")> <equals> value;
standard-gravitational-parameter ::= <"GM" (", km^3 s^-2" | " (km^3 s^-2)" | " (km^3/s^2)" )> <equals> value;
surface-area-title ::= "Surface Area:";
surface-area-land ::= <"land           = "> value <" "> unit-KMT;
surface-area-sea ::= <"sea            = "> value <" "> unit-KMT;
topo-spectral-fact ::= <"Topo. spectral fact t"> <equals> value;
visual-magnitude ::= <("Visual" | "Vis.") ws ("mag." | "magnitude") ws "V(1,0)"> <equals> value;
visual-magnitude-opposition ::= <"Vis. mag. (opposition)"> <equals> <"+"?> value;
volume ::= < "Volume" ","? " " "("? "x"? "10^"> exponent <" "> unit-H20 <")"?> <equals> value;
y-factor ::= <"Y factor (He/H ratio)"> <equals> value?;

obliquity-source ::= "[1] Margot et al., Science 316, 2007";

select-prompt ::= ("Select ... [E]phemeris, [F]tp, [M]ail, [R]edisplay, ?, <cr>: " |
                   ">>> Select... [A]gain, [N]ew-case, [F]tp, [K]ermit, [M]ail, [R]edisplay, ? : ");


bodies-line-item ::=  < "  " #"[ ]{0,6}">
                      body-id <"  ">
                      ((body-name        <" "+>) | <#"[ ]{34}">) <" ">
                      ((body-designation <" "+>) | <#"[ ]{11}">) <"  ">
                      ((body-aliases     <" "+>) | <#"[ ]{19}">);

body-designation ::= #"\d+\w*";
body-aliases ::= body-alias (" " body-alias)*;
body-alias ::= #"\w+";


<bodies-document> ::=
<garbage> <newline>
<separator> <newline>
<bodies-header> <newline>
(bodies-line-item <newline>)+
'        3  Earth-Moon Barycenter                           EMB' <ws>
'        4  Mars Barycenter' <ws>
'        5  Jupiter Barycenter' <ws>
'        6  Saturn Barycenter' <ws>
'        7  Uranus Barycenter' <ws>
'        8  Neptune Barycenter' <ws>
'        9  Pluto Barycenter' <ws>
'       10  Sun                                             Sol' <ws>
'      199  Mercury' <ws>
'      299  Venus' <ws>
'      301  Moon                                            Luna' <ws>
'      391  L1                                              S-E-M Lagrangian' <ws>
'      392  L2                                              S-E-M Lagrangian' <ws>
'      394  L4                                              S-E-M Lagrangian' <ws>
'      395  L5                                              S-E-M Lagrangian' <ws>
'      399  Earth                                           Geocenter' <ws>
'      401  Phobos                                          MI' <ws>
'      402  Deimos                                          MII' <ws>
'      499  Mars' <ws>
'      501  Io                                              JI' <ws>
'      502  Europa                                          JII' <ws>
'      503  Ganymede                                        JIII' <ws>
'      504  Callisto                                        JIV' <ws>
'      505  Amalthea                                        JV' <ws>
'      506  Himalia                                         JVI' <ws>
'      507  Elara                                           JVII' <ws>
'      508  Pasiphae                                        JVIII' <ws>
'      509  Sinope                                          JIX' <ws>
'      510  Lysithea                                        JX' <ws>
'      511  Carme                                           JXI' <ws>
'      512  Ananke                                          JXII' <ws>
'      513  Leda                                            JXIII' <ws>
'      514  Thebe                                           JXIV' <ws>
'      515  Adrastea                                        JXV' <ws>
'      516  Metis                                           JXVI' <ws>
bodies-line-item <ws>
'      518  Themisto                           1975J1       JXVIII 2000J1' <ws>
'      519  Megaclite                          2000J8       JXIX' <ws>
'      520  Taygete                            2000J9       JXX' <ws>
'      521  Chaldene                           2000J10      JXXI' <ws>
'      522  Harpalyke                          2000J5       JXXII' <ws>
'      523  Kalyke                             2000J2       JXXIII' <ws>
'      524  Iocaste                            2000J3       JXXIV' <ws>
'      525  Erinome                            2000J4       JXXV' <ws>
'      526  Isonoe                             2000J6       JXXVI' <ws>
'      527  Praxidike                          2000J7       JXXVII' <ws>
'      528  Autonoe                            2001J1       JXXVIII' <ws>
'      529  Thyone                             2001J2       JXXIX' <ws>
'      530  Hermippe                           2001J3       JXXX' <ws>
'      531  Aitne                              2001J11      JXXXI' <ws>
'      532  Eurydome                           2001J4       JXXXII' <ws>
'      533  Euanthe                            2001J7       JXXXIII' <ws>
'      534  Euporie                            2001J10      JXXXIV' <ws>
'      535  Orthosie                           2001J9       JXXXV' <ws>
'      536  Sponde                             2001J5       JXXXVI' <ws>
'      537  Kale                               2001J8       JXXXVII' <ws>
'      538  Pasithee                           2001J6       JXXXVIII' <ws>
'      539  Hegemone                           2003J8       JXXXIX' <ws>
'      540  Mneme                              2003J21      JXL' <ws>
'      541  Aoede                              2003J7       JXLI' <ws>
'      542  Thelxinoe                          2003J22      JXLII' <ws>
'      543  Arche                              2002J1       JXLIII' <ws>
'      544  Kallichore                         2003J11      JXLIV' <ws>
'      545  Helike                             2003J6       JXLV' <ws>
'      546  Carpo                              2003J20      JXLVI' <ws>
'      547  Eukelade                           2003J1       JXLVII' <ws>
'      548  Cyllene                            2003J13      JXLVIII' <ws>
'      549  Kore                               2003J14      JXLIX' <ws>
'      550  Herse                              2003J17      JXLXII' <ws>
'      551                                     2010J1       JLI' <ws>
'      552                                     2010J2       JLII' <ws>
'      553  Dia                                2000J11      JLIII' <ws>
'      554                                     2016J1       JLIV' <ws>
'      555                                     2003J18      JLV 55069' <ws>
'      556                                     2011J2       JLVI 55075' <ws>
'      557                                     2003J5       JLVII 55063' <ws>
'      558                                     2003J15      JLVIII 55067' <ws>
'      559                                     2017J1       JLIX' <ws>
bodies-line-item <newline>
'    55061                                     2003J3' <ws>
'    55062                                     2003J4' <ws>
'    55064                                     2003J9' <ws>
'    55065                                     2003J10' <ws>
'    55066                                     2003J12' <ws>
'    55068                                     2003J16' <ws>
'    55070                                     2003J19' <ws>
'    55071                                     2003J23' <ws>
'    55074                                     2011J1' <ws>
'      599  Jupiter' <ws>
'      601  Mimas                                           SI' <ws>
'      602  Enceladus                                       SII' <ws>
'      603  Tethys                                          SIII' <ws>
'      604  Dione                                           SIV' <ws>
'      605  Rhea                                            SV' <ws>
'      606  Titan                                           SVI' <ws>
'      607  Hyperion                                        SVII' <ws>
'      608  Iapetus                                         SVIII' <ws>
'      609  Phoebe                                          SIX' <ws>
'      610  Janus                                           SX' <ws>
'      611  Epimetheus                                      SXI' <ws>
'      612  Helene                                          SXII' <ws>
'      613  Telesto                                         SXIII' <ws>
'      614  Calypso                                         SXIV' <ws>
'      615  Atlas                                           SXV' <ws>
'      616  Prometheus                                      SXVI' <ws>
'      617  Pandora                                         SXVII' <ws>
'      618  Pan                                             SXVIII' <ws>
'      619  Ymir                               2000S1       SXIX' <ws>
'      620  Paaliaq                            2000S2       SXX' <ws>
'      621  Tarvos                             2000S4       SXXI' <ws>
'      622  Ijiraq                             2000S6       SXXII' <ws>
'      623  Suttungr                           2000S12      SXXIII' <ws>
'      624  Kiviuq                             2000S5       SXXIV' <ws>
'      625  Mundilfari                         2000S9       SXXV' <ws>
'      626  Albiorix                           2000S11      SXXVI' <ws>
'      627  Skathi                             2000S8       SXXVII' <ws>
'      628  Erriapus                           2000S10      SXXVIII' <ws>
'      629  Siarnaq                            2000S3       SXXIX' <ws>
'      630  Thrymr                             2000S7       SXXX' <ws>
'      631  Narvi                              2003S1       SXXXI' <ws>
'      632  Methone                            2004S1       SXXXII' <ws>
'      633  Pallene                            2004S2       SXXXIII' <ws>
'      634  Polydeuces                         2004S5       SXXXIV' <ws>
'      635  Daphnis                            2005S1       SXXXV' <ws>
'      636  Aegir                              2004S10      SXXXVI 65038' <ws>
'      637  Bebhionn                           2004S11      SXXXVII 65039' <ws>
'      638  Bergelmir                          2004S15      SXXXVIII 65043' <ws>
'      639  Bestla                             2004S18      SXXXIX 65046' <ws>
'      640  Farbauti                           2004S9       SXL 65037' <ws>
'      641  Fenrir                             2004S16      SXLI 65044' <ws>
'      642  Fornjot                            2004S8       SXLII 65036' <ws>
'      643  Hati                               2004S14      SXLIII' <ws>
'      644  Hyrrokkin                          2004S19      SXLIV' <ws>
'      645  Kari                               2006S2       SXLV' <ws>
'      646  Loge                               2006S5       SXLVI' <ws>
'      647  Skoll                              2006S8       SXLVII' <ws>
'      648  Surtur                             2006S7       SXLVIII' <ws>
'      649  Anthe                              2007S4       SXLIX' <ws>
'      650  Jarnsaxa                           2006S6       SL' <ws>
'      651  Greip                              2006S4       SLI' <ws>
'      652  Tarqeq                             2007S1       SLII' <ws>
'      653  Aegaeon                            2008S1       SLIII' <ws>
'    65035                                     2004S7' <ws>
'    65040                                     2004S12' <ws>
'    65041                                     2004S13' <ws>
'    65045                                     2004S17' <ws>
'    65048                                     2006S1' <ws>
'    65050                                     2006S3' <ws>
'    65055                                     2007S2' <ws>
'    65056                                     2007S3' <ws>
'      699  Saturn' <ws>
'      701  Ariel                                           UI' <ws>
'      702  Umbriel                                         UII' <ws>
'      703  Titania                                         UIII' <ws>
'      704  Oberon                                          UIV' <ws>
'      705  Miranda                                         UV' <ws>
'      706  Cordelia                                        UVI' <ws>
'      707  Ophelia                                         UVII' <ws>
'      708  Bianca                                          UVIII' <ws>
'      709  Cressida                                        UIX' <ws>
'      710  Desdemona                                       UX' <ws>
'      711  Juliet                                          UXI' <ws>
'      712  Portia                                          UXII' <ws>
'      713  Rosalind                                        UXIII' <ws>
'      714  Belinda                                         UXIV' <ws>
'      715  Puck                                            UXV' <ws>
'      716  Caliban                                         UXVI' <ws>
'      717  Sycorax                                         UXVII' <ws>
'      718  Prospero                           1999U3       UXVIII' <ws>
'      719  Setebos                            1999U1       UXIX' <ws>
'      720  Stephano                           1999U2       UXX' <ws>
'      721  Trinculo                           2001U1       UXXI' <ws>
'      722  Francisco                          2001U3       UXXII' <ws>
'      723  Margaret                           2003U3       UXXIII' <ws>
'      724  Ferdinand                          2001U2       UXXIV' <ws>
'      725  Perdita                            1986U10      UXXV' <ws>
'      726  Mab                                2003U1       UXXVI' <ws>
'      727  Cupid                              2003U2       UXXVII' <ws>
'      799  Uranus' <ws>
'      801  Triton                                          NI' <ws>
'      802  Nereid                                          NII' <ws>
'      803  Naiad                                           NIII' <ws>
'      804  Thalassa                                        NIV' <ws>
'      805  Despina                                         NV' <ws>
'      806  Galatea                                         NVI' <ws>
'      807  Larissa                                         NVII' <ws>
'      808  Proteus                                         NVIII' <ws>
'      809  Halimede                           2002N1' <ws>
'      810  Psamathe                           2003N1' <ws>
'      811  Sao                                2002N2' <ws>
'      812  Laomedeia                          2002N3' <ws>
'      813  Neso                               2002N4' <ws>
'      814  2004N1' <ws>
'      899  Neptune' <ws>
'      901  Charon                                          PI' <ws>
'      902  Nix                                             PII' <ws>
'      903  Hydra                                           PIII' <ws>
'      904  Kerberos                           2011P1' <ws>
'      905  Styx                               2012P1' <ws>
'      999  Pluto                              134340' <ws>
'       -2  Mariner 2 (spacecraft)' <ws>
'       -3  Mars Orbiter Mission (MOM) (spacec              Mangalyaan ISRO' <ws>
'       -5  Planet-C (spacecraft)                           VCO Akatsuki' <ws>
'       -6  Pioneer 6 (spacecraft)' <ws>
'      -12  LADEE (spacecraft)' <ws>
'      -18  LCROSS (spacecraft)' <ws>
'      -20  Pioneer 8 (spacecraft)' <ws>
'      -21  SOHO (spacecraft)' <ws>
'      -23  Pioneer 10 (spacecraft)' <ws>
'      -24  Pioneer 11 (spacecraft)' <ws>
'      -25  Lunar Prospector (LP) (spacecraft)' <ws>
'      -29  Stardust (bus) (spacecraft)                     NExT' <ws>
'   -29900  Stardust (SRC) (spacecraft)' <ws>
'      -30  Deep Space 1 (spacecraft)                       DS1 DS-1' <ws>
'      -31  Voyager 1 (spacecraft)' <ws>
'      -32  Voyager 2 (spacecraft)' <ws>
'      -37  Hayabusa 2 (spacecraft)' <ws>
'      -39  Ouna (spacecraft)' <ws>
'      -40  Clementine (spacecraft)                         DSPSE' <ws>
'      -41  Mars Express (spacecraft)                       MEX' <ws>
'      -47  Genesis (bus) (spacecraft)' <ws>
'      -48  Hubble Space Telescope                          HST (spacecraft)' <ws>
'   -47900  Genesis (SRC) (spacecraft)' <ws>
'      -53  Mars Odyssey (spacecraft)' <ws>
'      -55  Ulysses (spacecraft)' <ws>
'      -61  Juno (spacecraft)' <ws>
'      -64  OSIRIS-REx (spacecraft)                         ORX' <ws>
'      -70  Deep Impact IMPACTOR (spacecraft)' <ws>
'      -74  Mars Reconnaissance Orbiter (space              MRO' <ws>
'      -76  Mars Science Laboratory (spacecraf MSL' <ws>
'   -74900  MRO Centaur Stage (spacecraft)' <ws>
'      -77  Galileo (spacecraft)' <ws>
'      -78  DSCOVR (spacecraft)                             Triana' <ws>
'      -79  Spitzer Space Telescope                         SST SIRTF (spacecraf' <ws>
'      -82  Cassini (spacecraft)' <ws>
'      -84  Phoenix (spacecraft)' <ws>
'      -85  LRO (spacecraft)' <ws>
'      -86  CH1' <ws>
'      -93  NEAR (spacecraft)' <ws>
'      -98  New Horizons (spacecraft)                       NH New_Horizons' <ws>
'     -111  ICE (spacecraft)                                ISEE-3' <ws>
'     -130  Hayabusa (spacecraft)                           Muses-C' <ws>
'     -140  Deep Impact Flyby - EPOXI (spacecr              EPOXI' <ws>
'     -143  ExoMars TGO (spacecraft)' <ws>
'     -150  Cassini Huygens (spacecraft)' <ws>
'     -151  Chandra Observatory (spacecraft)' <ws>
'     -163  WISE (spacecraft)' <ws>
'     -165  WMAP (spacecraft)' <ws>
'     -170  James Webb Space Telescope (spacec              JWST' <ws>
'     -176  GRAIL-SS Second Stage (spacecraft)' <ws>
'     -177  GRAIL-A (spacecraft)                            Ebb' <ws>
'     -178  Nozomi (spacecraft)                             Planet-B' <ws>
'     -181  GRAIL-B (spacecraft)                            Flow' <ws>
'     -192  THEMIS-B (spacecraft)                           ARTEMIS-P1' <ws>
'     -193  THEMIS-C (spacecraft)                           ARTEMIS-P2' <ws>
'     -198  INTEGRAL (spacecraft)' <ws>
'     -202  MAVEN (spacecraft)' <ws>
'     -203  Dawn (spacecraft)' <ws>
'     -204  CONTOUR-A (SPACECRAFT FRAGMENT)' <ws>
'     -205  CONTOUR-B (SPACECRAFT FRAGMENT)' <ws>
'     -206  CONTOUR-C (SPACECRAFT FRAGMENT)' <ws>
'     -226  Rosetta (spacecraft)' <ws>
'     -227  Kepler (spacecraft)' <ws>
'     -234  STEREO-A (spacecraft)                           AHEAD' <ws>
'     -235  STEREO-B (spacecraft)                           BEHIND' <ws>
'  -234900  STEREO Third Stage (spacecraft)' <ws>
'     -236  MESSENGER (spacecraft)' <ws>
'     -248  Venus Express (spacecraft)                      VEX' <ws>
'     -253  Opportunity (spacecraft)                        MER' <ws>
'     -254  Spirit (spacecraft)                             MER' <ws>
'     -344  Galileo Probe (spacecraft)' <ws>
'     -486  Herschel Space Observatory (spacec' <ws>
'     -489  Planck Space Observatory (spacecra' <ws>
'     -557  Spektr-R Observatory (spacecraft)' <ws>
'     -610  Juno Centaur Stage (spacecraft)' <ws>
'     -640  Infrared Space Observatory (spacec              ISO' <ws>
'     -760  MSL Centaur Stage spacecraft' <ws>
'     -997  NEOCP 6Q0B44E                                   B44E' <ws>
'     -998  NEOCP J002E3' <ws>
'   -23230  ETS-6 (spacecraft)                              Kiku-6' <ws>
'  -399050  2015 PDC' <ws>
'  -399080  Apollo 8 S-IVB (spacecraft)' <ws>
'  -399090  Apollo 9 S-IVB (spacecraft)' <ws>
'  -399100  Apollo 10 S-IVB (spacecraft)' <ws>
'  -399101  Apollo 10 LM (spacecraft)                       Snoopy' <ws>
'  -399110  Apollo 11 S-IVB (spacecraft)' <ws>
'  -399120  Apollo 12 S-IVB (spacecraft)' <ws>
'  -108366  GOES-1 (spacecraft)' <ws>
'  -108820  LAGEOS-1 (spacecraft)' <ws>
'  -111353  FLTSATCOM 2 (spacecraft)' <ws>
'  -112065  SBS-1 (spacecraft)' <ws>
'  -112472  GOES-5 (spacecraft)' <ws>
'  -113631  SATCOM-C5 (spacecraft)             RCA-SATCOM-' <ws>
'  -114050  GOES-6 (spacecraft)' <ws>
'  -116908  AJISAI (spacecraft)' <ws>
'  -119548  TDRS-3 (spacecraft)' <ws>
'  -120452  NAVSTAR-18 (spacecraft)' <ws>
'  -122195  LAGEOS-2 (spacecraft)' <ws>
'  -122911  Solidaridad-1 (spacecraft)' <ws>
'  -122927  Telstar-401 (spacecraft)' <ws>
'  -123051  GOES-8 (spacecraft)' <ws>
'  -123553  AMSC-1 (spacecraft)' <ws>
'  -123846  MSAT-1 (spacecraft)' <ws>
'  -123754  Echostar-1 (spacecraft)' <ws>
'  -124313  Echostar-2 (spacecraft)' <ws>
'  -125126  HGS-1 (spacecraft)                              Asiasat-3 PAS-22' <ws>
'  -125544  International Space Station (space              ISS' <ws>
'  -125989  XMM-Newton (spacecraft)' <ws>
'  -126402  Echostar-6 (spacecraft)' <ws>
'  -126407  NAVSTAR-48 (spacecraft)' <ws>
'  -126639  AMC-8 (spacecraft)                              GE-8' <ws>
'  -127783  GALEX (spacecraft)' <ws>
'  -128485  Swift Observatory (spacecraft)' <ws>
'  -128868  Anik-F1R (spacecraft)' <ws>
'  -128884  Galaxy-15 (spacecraft)' <ws>
'  -129494  DirecTV-9S (spacecraft)' <ws>
'  -129520  XM-4 (spacecraft)' <ws>
'  -133207  Echostar-11 (spacecraft)' <ws>
'  -113269  WESTAR-5 (spacecraft)' <ws>
'  -134381  Kepler Booster (Third Stage) (spac' <ws>
'  -135491  GOES-14 (spacecraft)' <ws>
'  -136134' <ws>
'  -136395  Solar Dynamics Observatory (spacec              SDO' <ws>
'  -136499  Echostar-14 (spacecraft)' <ws>
'  -137218  SKYTERRA-1 (spacecraft)' <ws>
'  -137820  Tiangong-1 (spacecraft)' <ws>
'  -138250  BEIDOU-M3 (spacecraft)' <ws>
'  -138358  NuSTAR (spacecraft)                SMEX-11' <ws>
'  -138551  Echostar-17 (spacecraft)' <ws>
'  -138833  NAVSTAR-67 (spacecraft)' <ws>
'  -139166  NAVSTAR-68 (spacecraft)' <ws>
'  -139479  Gaia (spacecraft)' <ws>
'  -140482  MMS-1 (spacecraft)' <ws>
'  -140483  MMS-2 (spacecraft)' <ws>
'  -140484  MMS-3 (spacecraft)' <ws>
'  -140485  MMS-4 (spacecraft)' <ws>
'  -140663  DirecTV-15 (spacecraft)' <ws>
'  -141043  LISA Pathfinder (spacecraft)                    LPF' <ws>
'  -999742  LISA Pathfinder Propulsion Module               PRM' <ws>
'   999787  WT1190F' <ws>
'  -937001  2017 PDC                                        PDC17' <ws>
'  -937002  2017 PDCa                                       PDC17a' <ws>
'  1000012' <ws>
'  1000041  Hartley 2                          103P' <ws>
'  1000093' <ws>
'  1000107' <ws>
'  1003228  Siding Spring                      2013 A1' <ws>
'  9037734  ISON_NG1' <ws>
'  9037735  ISON_NG2' <ws>
'  2000001' <ws>
'  2000004' <ws>
'  2000433' <ws>
'  2006489  Golevka                            1991 JX      6489' <ws>
'  2101955' <ws>
'  2002867' <ws>
'  3430291  2008 TC3' <ws>
'  3713011' <ws>
'  9901490  9O0DC57 (spacecraft)' <ws>
'  9901885  9U01FF6 (spacecraft)' <ws>

'   Number of matches =  362. Use ID# to make unique selection.' <ws>
<separator> <ws>

bodies-header ::= ' Multiple major-bodies match string "*"' <ws>
                  '  ID#      Name                               Designation  IAU/aliases/other' <ws>
                  '  -------  ---------------------------------- -----------  ------------------- '
