S ::=
    <separator>, file-header,
    <newline>,   geophysical-data,
    <separator>, ephemeris-metadata,
    <separator>, targeting,
    <separator>, time-frame,
    <separator>, constants,
    <separator>, ephemeris-header,
    <separator>, ephemeris,
    <separator>, <footer>;

separator ::= (short-sep | long-sep), <whitespace>, separator?;
short-sep ::= #"\*{79}";
long-sep ::= #"\*{110}";

newline ::= "\n"
space ::= #"\s";
whitespace ::= (space* | newline*) whitespace*;

file-header ::= " Revised: Sep 28, 2012                 Mars                             499 / 4" <whitespace>

geophysical-data ::=
    <whitespace> geophysical-data-header
    <whitespace> "Mean radius (km)      = " "3389.9(2+-4)    "
    <whitespace> "Density (g cm^-3)     = " " 3.933(5+-4)"
    <whitespace> "Mass (10^23 kg )      = " "   6.4185       "
    <whitespace> "Flattening, f         = " " 1/154.409"
    <whitespace> "Volume (x10^10 km^3)  = " "  16.318        "
    <whitespace> "Semi-major axis       = " " 3397+-4"
    <whitespace> "Sidereal rot. period  = " "  24.622962 hr  "
    <whitespace> "Rot. Rate (x10^5 s)   = " " 7.088218"
    <whitespace> "Mean solar day        = " "   1.0274907 d  "
    <whitespace> "Polar gravity ms^-2   = " " 3.758"
    <whitespace> "Mom. of Inertia       = " "   0.366        "
    <whitespace> "Equ. gravity  ms^-2   = " " 3.71"
    <whitespace> "Core radius (km)      = " " ~1700          "
    <whitespace> "Potential Love # k2   = " " 0.153 +-.017"

    <whitespace> "Grav spectral fact u  = " "  14 (x10^5)    "
    <whitespace> "Topo. spectral fact t = " "96 (x10^5)"
    <whitespace> "Fig. offset (Rcf-Rcm) = " "2.50+-0.07 km   "
    <whitespace> "Offset (lat./long.)   = " "62d / 88d"
    <whitespace> "GM (km^3 s^-2)        = " "42828.3         "
    <whitespace> "Equatorial Radius, Re = " "3394.0 km"
    <whitespace> "GM 1-sigma (km^3 s^-2)= " "+- 0.1          "
    <whitespace> "Mass ratio (Sun/Mars) = " "3098708+-9"

    <whitespace> "Atmos. pressure (bar) = " "   0.0056       "
    <whitespace> "Max. angular diam.    = " ' 17.9\"'
    <whitespace> "Mean Temperature (K)  = " " 210            "
    <whitespace> "Visual mag. V(1,0)    = " " -1.52"
    <whitespace> "Geometric albedo      = " "   0.150        "
    <whitespace> "Obliquity to orbit    = " " 25.19 deg"
    <whitespace> "Mean sidereal orb per = " "   1.88081578 y "
    <whitespace> "Orbit vel.  km/s      = " " 24.1309"
    <whitespace> "Mean sidereal orb per = " " 686.98 d       "
    <whitespace> "Escape vel. km/s      = " "  5.027"
    <whitespace> "Hill's sphere rad. Rp = " " 319.8          "
    <whitespace> "Mag. mom (gauss Rp^3) = " "< 1x10^-4"
    <whitespace>

geophysical-data-header ::= "GEOPHYSICAL DATA (updated 2009-May-26):"

ephemeris-metadata ::=
"Ephemeris / WWW_USER Mon Mar  6 16:56:26 2017 Pasadena, USA      / Horizons" <whitespace>

targeting ::=
"Target body name: " "Mars (499)                      " "{source: mar097}" <whitespace>
"Center body name: " "Earth (399)                     " "{source: mar097}" <whitespace>
"Center-site name: " "GEOCENTRIC" <whitespace>

time-frame ::=
"Start time      : " "A.D. 2017-Feb-24 00:00:00.0000 UT" <whitespace>
"Stop  time      : " "A.D. 2017-Mar-26 00:00:00.0000 UT" <whitespace>
"Step-size       : " "1440 minutes" <whitespace>

constants ::=
"Target pole/equ : " "IAU_MARS                        " "{East-longitude -}" <whitespace>
"Target radii    : " "3396.2 x 3396.2 x 3376.2 km     " "{Equator, meridian, pole}" <whitespace>
"Center geodetic : " "0.00000000,0.00000000,0.0000000 " "{E-lon(deg),Lat(deg),Alt(km)}" <whitespace>
"Center cylindric: " "0.00000000,0.00000000,0.0000000 " "{E-lon(deg),Dxy(km),Dz(km)}" <whitespace>
"Center pole/equ : " "High-precision EOP model        " "{East-longitude +}" <whitespace>
"Center radii    : " "6378.1 x 6378.1 x 6356.8 km     " "{Equator, meridian, pole}" <whitespace>
"Target primary  : " "Sun" <whitespace>
"Vis. interferer : " "MOON (R_eq= 1737.400) km        " "{source: mar097}" <whitespace>
"Rel. light bend : " "Sun, EARTH                      " "{source: mar097}" <whitespace>
"Rel. lght bnd GM: " "1.3271E+11, 3.9860E+05 km^3/s^2" <whitespace>
"Atmos refraction: " "NO (AIRLESS)" <whitespace>
"RA format       : " "HMS" <whitespace>
"Time format     : " "CAL" <whitespace>
"EOP file        : " "eop.170306.p170528" <whitespace>
"EOP coverage    : " "DATA-BASED 1962-JAN-20 TO 2017-MAR-06. PREDICTS-> 2017-MAY-27" <whitespace>
"Units conversion: " "1 au= 149597870.700 km, c= 299792.458 km/s, 1 day= 86400.0 s" <whitespace>
"Table cut-offs 1: " "Elevation (-90.0deg=NO ),Airmass (>38.000=NO), Daylight (NO )" <whitespace>
"Table cut-offs 2: " "Solar Elongation (  0.0,180.0=NO ),Local Hour Angle( 0.0=NO )" <whitespace>

ephemeris-header ::= " Date__(UT)__HR:MN     R.A._(ICRF/J2000.0)_DEC  APmag  S-brt            delta      deldot    S-O-T /r    S-T-O" <whitespace>

ephemeris ::= <"$$SOE">, <whitespace>, ephemeris-line-item+, <"$$EOE">, <whitespace>;

ephemeris-line-item ::=
    <whitespace>, timestamp,
    <whitespace>, ascension-declination,
    <whitespace>, apparent-magnitude,
    <whitespace>, surface-brightness,
    <whitespace>, range,
    <whitespace>, range-rate,
    <whitespace>, sun-observer-target-angle,
    <whitespace>, sun-observer-target-angle-direction,
    <whitespace>, sun-target-observer-angle,
    <whitespace>;

timestamp ::= date, <whitespace>, time;

<date> ::= year <"-"> month <"-"> day;

year ::= "2017";
month ::= "Jan" | "Feb" | "Mar" | "Apr" | "May" | "Jun" | "Jul" | "Aug" | "Sep" | "Oct" | "Nov" | "Dec";
day ::= #"[0-9]{2}";
time ::= #"\d\d:\d\d";

ascension-declination ::= #"\d\d \d\d \d\d\.\d\d \+\d\d \d\d \d\d\.\d";

apparent-magnitude ::= #"\d\.\d\d";

surface-brightness ::= #"\d\.\d\d";

range ::= #"\d\.\d{14}";
range-rate ::= #"\d\d\.\d{7}";
sun-observer-target-angle ::= #"\d\d\.\d\d\d\d";

sun-observer-target-angle-direction ::= "/T" | "/L";

sun-target-observer-angle ::= #"\d\d\.\d{4}";

footer ::= "Column meaning:", #"[\s\S\w\W.]*";